name: prosmith
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - pytorch
  - cudatoolkit
  - pandas
  - numpy
  - biopython
  - transformers
  - fair-esm
  - scikit-learn
  - lifelines
  - xgboost
  - hyperopt
